version: "3.7"
services:
  ProjectZomboidDedicatedServer:
    image: danixu86/project-zomboid-dedicated-server:${IMAGE_TAG:-42.13.2-unstable}
    restart: unless-stopped
    environment:
      - IMAGE_TAG=${IMAGE_TAG:-42.13.2-unstable}
      - STEAMAPPBRANCH=${STEAMAPPBRANCH:-unstable}
      - FORCEUPDATE=${FORCEUPDATE:-false}
      - FORCESTEAMCLIENTSOUPDATE=${FORCESTEAMCLIENTSOUPDATE:-false}
      - LANG=${LANG:-en_EN.UTF-8}
      - NOSTEAM=${NOSTEAM:-false}
      - CACHEDIR=${CACHEDIR:-}
      - MODFOLDERS=${MODFOLDERS:-workshop,steam,mods}
      - DEBUG=${DEBUG:-false}
      - ADMINUSERNAME=${ADMINUSERNAME:-admin}
      - ADMINPASSWORD=${ADMINPASSWORD:-}
      - SERVERNAME=${SERVERNAME:-servertest}
      - SERVERPRESET=${SERVERPRESET:-}
      - SERVERPRESETREPLACE=${SERVERPRESETREPLACE:-false}
      - COOP=${COOP:-false}
      - IP=${IP:-}
      - PORT=${PORT:-16261}
      - STEAMVAC=${STEAMVAC:-true}
      - STEAMPORT1=${STEAMPORT1:-}
      - STEAMPORT2=${STEAMPORT2:-}
      - MIN_MEMORY=${MIN_MEMORY:-}
      - MAX_MEMORY=${MAX_MEMORY:-}
      - MEMORY=${MEMORY:-2048m}
      - SOFTRESET=${SOFTRESET:-false}
      - PASSWORD=${PASSWORD:-}
      - RCONPASSWORD=${RCONPASSWORD:-}
      - PUBLIC=${PUBLIC:-}
      - DISPLAYNAME=${DISPLAYNAME:-}
      - SELF_MANAGED_MODS=${SELF_MANAGED_MODS:-true}
      - MOD_IDS=${MOD_IDS-}
      - WORKSHOP_IDS=${WORKSHOP_IDS-}
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    volumes:
      # Server data
      - /root/zomboid/data:/home/steam/Zomboid
      # Workshop mods folder
      - /root/zomboid/workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
      # Use scripts from this repo without rebuilding the image
      - /root/zomboid/scripts/entry.sh:/server/scripts/entry.sh:ro
      - /root/zomboid/scripts/search_folder.sh:/server/scripts/search_folder.sh:ro
      - /root/zomboid/scripts/fix_workshop_case.sh:/server/scripts/fix_workshop_case.sh:ro
