version: "3.7"
services:
  ProjectZomboidDedicatedServer:
    image: danixu86/project-zomboid-dedicated-server:${STEAMAPPBRANCH:-42.13.2-unstable}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    volumes:
      # Server data
      - ${DATA_HOST_PATH:-./data}:${CACHEDIR:-/home/steam/Zomboid}
      # Workshop mods folder
      - ${WORKSHOP_HOST_PATH:-./workshop-mods}:/home/steam/pz-dedicated/steamapps/workshop
